<?php
$categorias = array ( "GF" => array ("0","Grandes Formatos"),
					  "ID" => array ("0", "Impressão digital"),
					  "ID1" => array ("ID", "Envelopes"),
					  "ID2" => array ("ID", "Papel 80g"),
					  "D2" => array ("ID", "Cartolina"),
					  "IO" => array ("0", "Impressão offset"),
					  "AC" => array ("0", "Acabamentos")
					)  ;  // categorias [] [0]..., 
	  	  
$artigos = array ( "I01"  => array ( "nome" => "Livros, teses e currículos",
									"cat" => "ID",
									"tipo" => "trabalho composto",
									"images"=> "xxx.png",
									"bases" => array ("basec" => array ( "nome" => "Páginas a cores",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,
													"basep" => array ( "nome" => "Páginas a Preto e Branco",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => ".5",
																		                 "101-1000" => ".4",
																		                 "101-..." => ".3"))) ,
									"comp" => array ("enc01" => array ( "nome" => "Encadernação Espiral metálica",
																		"tip" => "0",													 
																		"uni" => "intervalo",
																		"val" => "INT",
																		"preco" => array("0-100" => "2.5",
																		                 "101-1000" => "2",
																		                 "101-..." => "1.5")  ) ,		
													"enc02" => array ( "nome" => "Encadernação arame duplo",
																		"tip" => "0",													 
																		"uni" => "intervalo",
																		"val" => "INT",
																		"preco" => array("0-100" => "5",
																		                 "101-1000" => "4",
																		                 "101-..." => "3")  ) ,		
													"enc03" => array ( "nome" => "Encadernação tipo Livro",
																		"tip" => "0",													 
																		"uni" => "intervalo",
																		"val" => "INT",
																		"preco" => array("0-100" => "12",
																		                 "101-1000" => "11",
																		                 "101-..." => "10")  ) ,
												    "cd01" => array ( "nome" => "CD simples",
																		"tip" => "0",													 
																		"uni" => "CDs",
																		"val" => "QTD",
																		"preco" => "1"  ) ,
													"cd02" => array ( "nome" => "CD Impresso",
																		"tip" => "0",													 
																		"uni" => "CDs",
																		"val" => "QTD",
																		"preco" => "2"  ) ) ),							
				    "I02"  => array ("nome" => "Folhetos",
									"cat" => "ID",
									"tipo" => "trabalho composto",
									"images" => "xxx.png",
									"bases" => array ( "base01" => array ( "nome" => "1/1 Cor preto",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3") ) ,
													"base02" => array ( "nome" => "2/2 Cor preto + Pantone",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3") ) ,									 
													"base03" => array ( "nome" => "4/4 Colorido CMYK",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3") ) ),
									"comp" => array ( "tratamento01" => array ( "nome" => "Cortar",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "11.5",
																		                 "101-1000" => "11.4",
																		                 "101-..." => "11.3") ) ,									 									 
													"tratamento02" => array ( "nome" => "Cortar e Arredondar cantos",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,									 									 									 
													"perfuracao01" => array ( "nome" => "Linhas de perfuração 1",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,									 									 									 									 
													"perfuracao02" => array ( "nome" => "Linhas de perfuração 4",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,
													"Refinacao01" => array ( "nome" => "Sem refinação",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,									 
													"Refinacao02" => array ( "nome" => "Verniz Localizado",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3") ) ) ),
					"I03"  => array ( "nome" => "Envelopes 162x226 Com janela à esquerda  ",
									"cat" => "ID1",
									"tipo" => "trabalho composto",
									"alter" => array ( 
									"formato01" => array ( "nome" => "",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,
									"formato02" => array ( "nome" => "120x220 Comprido sem janela",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,
									"base01" => array ( "nome" => "1/1 Cor preto",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,
									"base02" => array ( "nome" => "2/2 Cor preto + Pantone",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,									 
									"base03" => array ( "nome" => "4/4 Colorido CMYK",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,					
									"papel03" => array ( "nome" => "Colagem aderente, offset (interior cinzento impresso)",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3") ) ) ),
								"I04"  => array ( "nome" => "120x220 Comprido sem janela",
									"cat" => "ID1",
									"tipo" => "trabalho composto",
									"alter" => array ( 
									"formato01" => array ( "nome" => "",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,
									"formato02" => array ( "nome" => "",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,
									"base01" => array ( "nome" => "1/1 Cor preto",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,
									"base02" => array ( "nome" => "2/2 Cor preto + Pantone",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,									 
									"base03" => array ( "nome" => "4/4 Colorido CMYK",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,					
									"papel03" => array ( "nome" => "Colagem aderente, offset (interior cinzento impresso)",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3") ) ) )																					 
																						 
																						 
) ;
				
?>