<?php
$categorias = array ( "GF" => "Grandes Formatos",
					  "ID" => "Impressão digital",
					  "IO" => "Impressão offset",
					  "AC" => "Acabamentos"
					)  ;
	  	  
$artigos = array ( "I01"  => array ( "nome" => "Livros, teses e currículos",
									"cat" => "ID",
									"tipo" => "trabalho composto",
									"images"=> "xxx.png",
									"comp" => array ( "basec" => array ( "nome" => "Páginas a cores",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,
													"basep" => array ( "nome" => "Páginas a Preto e Branco",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => ".5",
																		                 "101-1000" => ".4",
																		                 "101-..." => ".3")  ) ,									 
													"enc01" => array ( "nome" => "Encadernação Espiral metálica",
																		"tip" => "0",													 
																		"uni" => "intervalo",
																		"val" => "INT",
																		"preco" => array("0-100" => "2.5",
																		                 "101-1000" => "2",
																		                 "101-..." => "1.5")  ) ,		
													"enc02" => array ( "nome" => "Encadernação arame duplo",
																		"tip" => "0",													 
																		"uni" => "intervalo",
																		"val" => "INT",
																		"preco" => array("0-100" => "5",
																		                 "101-1000" => "4",
																		                 "101-..." => "3")  ) ,		
													"enc03" => array ( "nome" => "Encadernação tipo Livro",
																		"tip" => "0",													 
																		"uni" => "intervalo",
																		"val" => "INT",
																		"preco" => array("0-100" => "12",
																		                 "101-1000" => "11",
																		                 "101-..." => "10")  ) ,
												    "cd01" => array ( "nome" => "CD simples",
																		"tip" => "0",													 
																		"uni" => "CDs",
																		"val" => "QTD",
																		"preco" => "1"  ) ,
													"cd02" => array ( "nome" => "CD Impresso",
																		"tip" => "0",													 
																		"uni" => "CDs",
																		"val" => "QTD",
																		"preco" => "2"  ) ) ),							
				    "I02"  => array ( "nome" => "Folhetos",
									"cat" => "ID",
									"tipo" => "trabalho composto",
									"images"=> "xxx.png",
									"comp" => array ( "base01" => array ( "nome" => "1/1 Cor preto",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3") ) ,
													"base02" => array ( "nome" => "2/2 Cor preto + Pantone",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3") ) ,									 
													"base03" => array ( "nome" => "4/4 Colorido CMYK",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,									 									 
													"tratamento01" => array ( "nome" => "Cortar",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "11.5",
																		                 "101-1000" => "11.4",
																		                 "101-..." => "11.3") ) ,									 									 
													"tratamento02" => array ( "nome" => "Cortar e Arredondar cantos",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,									 									 									 
													"perfuracao01" => array ( "nome" => "Linhas de perfuração 1",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,									 									 									 									 
													"perfuracao02" => array ( "nome" => "Linhas de perfuração 4",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,
													"Refinacao01" => array ( "nome" => "Sem refinação",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,									 
													"Refinacao02" => array ( "nome" => "Verniz Localizado",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3") ) ) ),
					"I03"  => array ( "nome" => "Envelopes",
									"cat" => "ID",
									"tipo" => "trabalho composto",
									"comp" => array ( 
									"formato01" => array ( "nome" => "162x226 Com janela à esquerda",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,
									"formato02" => array ( "nome" => "120x220 Comprido sem janela",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "21.5",
																		                 "101-1000" => "21.4",
																		                 "101-..." => "21.3")  ) ,
									"base01" => array ( "nome" => "1/1 Cor preto",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,
									"base02" => array ( "nome" => "2/2 Cor preto + Pantone",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,									 
									"base03" => array ( "nome" => "4/4 Colorido CMYK",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3")  ) ,					
									"papel03" => array ( "nome" => "Colagem aderente, offset (interior cinzento impresso)",
																		"tip" => "0",
																		"uni" => "página",
																		"val" => "UNI",
																		"preco" => array("0-100" => "1.5",
																		                 "101-1000" => "1.4",
																		                 "101-..." => "1.3") ) ))
) ;
				
?>